### ISSUE TITLE
SQLite3 support

### ISSUE THREAD

**Issue by Zhomart** [fridgerator/crecto#54]
I started implemented it. It's still in early stage right now.

- [x] insert command
- [ ] other things

https://github.com/Zhomart/crecto/tree/sqlite3

**Comment by fridgerator** [comment]
nice!

**Comment by fridgerator** [comment]
done!

**Comment by Zhomart** [comment]
Currently [fix](https://github.com/crystal-lang/crystal-sqlite3/pull/19) for Time and `Int32?`, `Bool` is not accepted yet, need to use `Zhomart/crystal-sqlite3:master`

shard.yml

```yml
dependencies:
  sqlite3:
    github: Zhomart/crystal-sqlite3
    # github: crystal-lang/crystal-sqlite3
    branch: master
  crecto:
    github: Zhomart/crecto
    branch: sqlite3
```
